# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6uD_cfNxEv6X7wPCLf2bOZZsO-m4ezL
"""

import serial
import time
from datetime import datetime
import webbrowser
import urllib.parse
import pyautogui

# --- Serial Communication Settings ---
ARDUINO_PORT = 'COM6'    # Change to your Arduino's serial port (e.g., 'COM3', '/dev/ttyACM0')
BAUD_RATE = 9600         # Must match the Arduino code's Serial.begin()

# --- WhatsApp Configuration ---
WHATSAPP_NUMBER = "+201114384075" # Target WhatsApp number (international format)
LOG_FILE = "attendance_log.csv"  # Attendance log file

# --- Automation Settings ---
WHATSAPP_LOAD_DELAY = 10 # Seconds to wait for WhatsApp Web to load

def send_whatsapp_message(user_id: str):
    """
    Opens WhatsApp Web, sends the notification, and logs the attendance.
    Relies on WhatsApp Web being logged in on the default browser.
    """
    now = datetime.now()
    timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

    # 1. Prepare the Message
    message = f"Attendance logged for User ID = {user_id} at {timestamp}"
    print("Preparing message:", message)

    # 2. URL Encoding and Opening WhatsApp Web
    encoded_msg = urllib.parse.quote(message)
    url = f"https://web.whatsapp.com/send?phone={WHATSAPP_NUMBER}&text={encoded_msg}"

    print("Opening WhatsApp Web...")
    webbrowser.open(url)

    # 3. Wait for the page to load
    print(f"Waiting {WHATSAPP_LOAD_DELAY} seconds for WhatsApp Web to load...")
    time.sleep(WHATSAPP_LOAD_DELAY)

    # 4. Automate Send (using pyautogui to click/press Enter)

    # Disable PyAutoGUI safety checks if running in a remote/headless environment
    # pyautogui.FAILSAFE = False

    # Get screen dimensions for approximate click location (Bottom Center)
    screen_w, screen_h = pyautogui.size()

    # Click near the message input box (adjust coordinates if needed)
    # This clicks roughly in the bottom middle of the screen
    pyautogui.click(screen_w // 2, screen_h - 100)
    time.sleep(1)

    # Send the message by pressing Enter
    print("Sending WhatsApp message now by pressing ENTER...")
    pyautogui.press("enter")
    time.sleep(1)

    print("Message sent successfully!")

    # 5. Log Attendance in CSV
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"{timestamp},{user_id}\n")

    print("Attendance saved.\n----------------------------------------")


def main():
    print(f"Connecting to Arduino on {ARDUINO_PORT}...")
    try:
        # Initialize Serial connection
        ser = serial.Serial(ARDUINO_PORT, BAUD_RATE, timeout=1)
        time.sleep(2) # Wait for Arduino to boot

        print("Listening for LOGIN: events from Arduino...\n")

        while True:
            # Read and decode line from Arduino
            line = ser.readline().decode('utf-8', errors='ignore').strip()

            if not line:
                continue

            print("FROM ARDUINO:", line)

            # Check if Arduino signaled a successful login
            if line.startswith("LOGIN:"):
                user_id = line.split(":")[1].strip()

                if user_id.isdigit():
                    send_whatsapp_message(user_id)
                else:
                    print("Error: Received invalid User ID format.")

    except serial.SerialException as e:
        print(f"ERROR: Could not connect to Arduino on {ARDUINO_PORT}. Please check connection and port setting.")
        print(f"Details: {e}")

    except KeyboardInterrupt:
        print("\nExiting by user interrupt...")

    except Exception as e:
        print(f"An unexpected error occurred: {e}")

    finally:
        if 'ser' in locals() and ser.is_open:
            ser.close()
            print("Serial connection closed.")


if __name__ == "__main__":
    main()